// <auto-generated />
namespace Framework.Forms
{
    partial class ShowServiceFormSettingCreation
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.radioButtonFullAffinity = new System.Windows.Forms.RadioButton();
            this.groupBoxAffinity = new System.Windows.Forms.GroupBox();
            this.comboBoxAccount = new System.Windows.Forms.ComboBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.textBoxPassword = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.textBoxUsername = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.textBoxDescription = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.textBoxDisplayName = new System.Windows.Forms.TextBox();
            this.radioButtonCustomAffinity = new System.Windows.Forms.RadioButton();
            this.label1 = new System.Windows.Forms.Label();
            this.textBoxWindowsNTServiceName = new System.Windows.Forms.TextBox();
            this.radioButtonUninstall = new System.Windows.Forms.RadioButton();
            this.radioButtonInstallAndRun = new System.Windows.Forms.RadioButton();
            this.radioButtonInstall = new System.Windows.Forms.RadioButton();
            this.buttonClone = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.groupBoxRun = new System.Windows.Forms.GroupBox();
            this.label7 = new System.Windows.Forms.Label();
            this.buttonCreate = new System.Windows.Forms.Button();
            this.linkLabel2 = new System.Windows.Forms.LinkLabel();
            this.label8 = new System.Windows.Forms.Label();
            this.groupBoxServiceOperationOption = new System.Windows.Forms.GroupBox();
            this.label9 = new System.Windows.Forms.Label();
            this.button1 = new System.Windows.Forms.Button();
            this.buttonSettings = new System.Windows.Forms.Button();
            this.buttonRunConsole = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label13 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.textBoxRESTEndpoint = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.propertyGrid1 = new System.Windows.Forms.PropertyGrid();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.linkLabel1 = new System.Windows.Forms.LinkLabel();
            this.checkBoxConsole = new System.Windows.Forms.CheckBox();
            this.linkLabel3 = new System.Windows.Forms.LinkLabel();
            this.checkBox2 = new System.Windows.Forms.CheckBox();
            this.groupBoxAffinity.SuspendLayout();
            this.groupBoxRun.SuspendLayout();
            this.groupBoxServiceOperationOption.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // radioButtonFullAffinity
            // 
            this.radioButtonFullAffinity.AutoSize = true;
            this.radioButtonFullAffinity.Checked = true;
            this.radioButtonFullAffinity.Location = new System.Drawing.Point(6, 18);
            this.radioButtonFullAffinity.Name = "radioButtonFullAffinity";
            this.radioButtonFullAffinity.Size = new System.Drawing.Size(99, 21);
            this.radioButtonFullAffinity.TabIndex = 0;
            this.radioButtonFullAffinity.TabStop = true;
            this.radioButtonFullAffinity.Text = "Setting File";
            this.radioButtonFullAffinity.UseVisualStyleBackColor = true;
            this.radioButtonFullAffinity.CheckedChanged += new System.EventHandler(this.RadioButtonFullAffinityCheckedChanged);
            // 
            // groupBoxAffinity
            // 
            this.groupBoxAffinity.Controls.Add(this.comboBoxAccount);
            this.groupBoxAffinity.Controls.Add(this.label6);
            this.groupBoxAffinity.Controls.Add(this.label5);
            this.groupBoxAffinity.Controls.Add(this.textBoxPassword);
            this.groupBoxAffinity.Controls.Add(this.label4);
            this.groupBoxAffinity.Controls.Add(this.textBoxUsername);
            this.groupBoxAffinity.Controls.Add(this.label3);
            this.groupBoxAffinity.Controls.Add(this.textBoxDescription);
            this.groupBoxAffinity.Controls.Add(this.label2);
            this.groupBoxAffinity.Controls.Add(this.textBoxDisplayName);
            this.groupBoxAffinity.Controls.Add(this.radioButtonCustomAffinity);
            this.groupBoxAffinity.Controls.Add(this.label1);
            this.groupBoxAffinity.Controls.Add(this.textBoxWindowsNTServiceName);
            this.groupBoxAffinity.Controls.Add(this.radioButtonFullAffinity);
            this.groupBoxAffinity.Enabled = false;
            this.groupBoxAffinity.Location = new System.Drawing.Point(8, 72);
            this.groupBoxAffinity.Name = "groupBoxAffinity";
            this.groupBoxAffinity.Size = new System.Drawing.Size(335, 214);
            this.groupBoxAffinity.TabIndex = 8;
            this.groupBoxAffinity.TabStop = false;
            this.groupBoxAffinity.Text = "Setting Options";
            // 
            // comboBoxAccount
            // 
            this.comboBoxAccount.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxAccount.Enabled = false;
            this.comboBoxAccount.FormattingEnabled = true;
            this.comboBoxAccount.Location = new System.Drawing.Point(108, 128);
            this.comboBoxAccount.Name = "comboBoxAccount";
            this.comboBoxAccount.Size = new System.Drawing.Size(218, 24);
            this.comboBoxAccount.TabIndex = 7;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(6, 190);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(69, 17);
            this.label6.TabIndex = 5;
            this.label6.Text = "Password";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(6, 162);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(73, 17);
            this.label5.TabIndex = 5;
            this.label5.Text = "Username";
            // 
            // textBoxPassword
            // 
            this.textBoxPassword.Enabled = false;
            this.textBoxPassword.Location = new System.Drawing.Point(108, 185);
            this.textBoxPassword.Name = "textBoxPassword";
            this.textBoxPassword.PasswordChar = '*';
            this.textBoxPassword.Size = new System.Drawing.Size(218, 22);
            this.textBoxPassword.TabIndex = 9;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(6, 134);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(59, 17);
            this.label4.TabIndex = 5;
            this.label4.Text = "Account";
            // 
            // textBoxUsername
            // 
            this.textBoxUsername.Enabled = false;
            this.textBoxUsername.Location = new System.Drawing.Point(108, 157);
            this.textBoxUsername.Name = "textBoxUsername";
            this.textBoxUsername.Size = new System.Drawing.Size(218, 22);
            this.textBoxUsername.TabIndex = 8;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(6, 106);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(79, 17);
            this.label3.TabIndex = 8;
            this.label3.Text = "Description";
            // 
            // textBoxDescription
            // 
            this.textBoxDescription.Enabled = false;
            this.textBoxDescription.Location = new System.Drawing.Point(108, 101);
            this.textBoxDescription.Name = "textBoxDescription";
            this.textBoxDescription.Size = new System.Drawing.Size(218, 22);
            this.textBoxDescription.TabIndex = 6;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(6, 78);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(95, 17);
            this.label2.TabIndex = 6;
            this.label2.Text = "Display Name";
            // 
            // textBoxDisplayName
            // 
            this.textBoxDisplayName.Enabled = false;
            this.textBoxDisplayName.Location = new System.Drawing.Point(108, 73);
            this.textBoxDisplayName.Name = "textBoxDisplayName";
            this.textBoxDisplayName.Size = new System.Drawing.Size(218, 22);
            this.textBoxDisplayName.TabIndex = 5;
            // 
            // radioButtonCustomAffinity
            // 
            this.radioButtonCustomAffinity.AutoSize = true;
            this.radioButtonCustomAffinity.Location = new System.Drawing.Point(110, 18);
            this.radioButtonCustomAffinity.Name = "radioButtonCustomAffinity";
            this.radioButtonCustomAffinity.Size = new System.Drawing.Size(124, 21);
            this.radioButtonCustomAffinity.TabIndex = 1;
            this.radioButtonCustomAffinity.Text = "Custom Setting";
            this.radioButtonCustomAffinity.UseVisualStyleBackColor = true;
            this.radioButtonCustomAffinity.CheckedChanged += new System.EventHandler(this.RadioButtonCustomAffinityCheckedChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(6, 50);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(96, 17);
            this.label1.TabIndex = 3;
            this.label1.Text = "Service Name";
            // 
            // textBoxWindowsNTServiceName
            // 
            this.textBoxWindowsNTServiceName.Enabled = false;
            this.textBoxWindowsNTServiceName.Location = new System.Drawing.Point(108, 45);
            this.textBoxWindowsNTServiceName.Name = "textBoxWindowsNTServiceName";
            this.textBoxWindowsNTServiceName.Size = new System.Drawing.Size(218, 22);
            this.textBoxWindowsNTServiceName.TabIndex = 4;
            // 
            // radioButtonUninstall
            // 
            this.radioButtonUninstall.AutoSize = true;
            this.radioButtonUninstall.Location = new System.Drawing.Point(231, 23);
            this.radioButtonUninstall.Name = "radioButtonUninstall";
            this.radioButtonUninstall.Size = new System.Drawing.Size(83, 21);
            this.radioButtonUninstall.TabIndex = 12;
            this.radioButtonUninstall.Text = "Uninstall";
            this.radioButtonUninstall.UseVisualStyleBackColor = true;
            this.radioButtonUninstall.CheckedChanged += new System.EventHandler(this.RadioButtonUninstallCheckedChanged);
            // 
            // radioButtonInstallAndRun
            // 
            this.radioButtonInstallAndRun.AutoSize = true;
            this.radioButtonInstallAndRun.Location = new System.Drawing.Point(98, 23);
            this.radioButtonInstallAndRun.Name = "radioButtonInstallAndRun";
            this.radioButtonInstallAndRun.Size = new System.Drawing.Size(123, 21);
            this.radioButtonInstallAndRun.TabIndex = 11;
            this.radioButtonInstallAndRun.Text = "Install and Run";
            this.radioButtonInstallAndRun.UseVisualStyleBackColor = true;
            this.radioButtonInstallAndRun.CheckedChanged += new System.EventHandler(this.RadioButtonInstallAndRunCheckedChanged);
            // 
            // radioButtonInstall
            // 
            this.radioButtonInstall.AutoSize = true;
            this.radioButtonInstall.Checked = true;
            this.radioButtonInstall.Location = new System.Drawing.Point(9, 23);
            this.radioButtonInstall.Name = "radioButtonInstall";
            this.radioButtonInstall.Size = new System.Drawing.Size(65, 21);
            this.radioButtonInstall.TabIndex = 10;
            this.radioButtonInstall.TabStop = true;
            this.radioButtonInstall.Text = "Install";
            this.radioButtonInstall.UseVisualStyleBackColor = true;
            this.radioButtonInstall.CheckedChanged += new System.EventHandler(this.RadioButtonInstallCheckedChanged);
            // 
            // buttonClone
            // 
            this.buttonClone.Location = new System.Drawing.Point(349, 220);
            this.buttonClone.Name = "buttonClone";
            this.buttonClone.Size = new System.Drawing.Size(132, 30);
            this.buttonClone.TabIndex = 13;
            this.buttonClone.Text = "Clone it";
            this.buttonClone.UseVisualStyleBackColor = true;
            this.buttonClone.Click += new System.EventHandler(this.ButtonGoClick);
            // 
            // buttonCancel
            // 
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new System.Drawing.Point(443, 653);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size(132, 30);
            this.buttonCancel.TabIndex = 14;
            this.buttonCancel.Text = "Cancel";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new System.EventHandler(this.ButtonCancelClick);
            // 
            // groupBoxRun
            // 
            this.groupBoxRun.Controls.Add(this.label7);
            this.groupBoxRun.Controls.Add(this.buttonCreate);
            this.groupBoxRun.Controls.Add(this.linkLabel2);
            this.groupBoxRun.Controls.Add(this.label8);
            this.groupBoxRun.Controls.Add(this.groupBoxServiceOperationOption);
            this.groupBoxRun.Controls.Add(this.label9);
            this.groupBoxRun.Controls.Add(this.button1);
            this.groupBoxRun.Controls.Add(this.groupBoxAffinity);
            this.groupBoxRun.Controls.Add(this.buttonClone);
            this.groupBoxRun.Location = new System.Drawing.Point(12, 286);
            this.groupBoxRun.Name = "groupBoxRun";
            this.groupBoxRun.Size = new System.Drawing.Size(563, 361);
            this.groupBoxRun.TabIndex = 12;
            this.groupBoxRun.TabStop = false;
            this.groupBoxRun.Text = "Windows NT Service";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(208, 52);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(145, 17);
            this.label7.TabIndex = 29;
            this.label7.Text = "More details available";
            // 
            // buttonCreate
            // 
            this.buttonCreate.Location = new System.Drawing.Point(349, 256);
            this.buttonCreate.Name = "buttonCreate";
            this.buttonCreate.Size = new System.Drawing.Size(132, 30);
            this.buttonCreate.TabIndex = 20;
            this.buttonCreate.Text = "Create";
            this.buttonCreate.UseVisualStyleBackColor = true;
            this.buttonCreate.Click += new System.EventHandler(this.buttonCreate_Click);
            // 
            // linkLabel2
            // 
            this.linkLabel2.AutoSize = true;
            this.linkLabel2.Location = new System.Drawing.Point(359, 52);
            this.linkLabel2.Name = "linkLabel2";
            this.linkLabel2.Size = new System.Drawing.Size(39, 17);
            this.linkLabel2.TabIndex = 28;
            this.linkLabel2.TabStop = true;
            this.linkLabel2.Text = "Here";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(208, 35);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(342, 17);
            this.label8.TabIndex = 27;
            this.label8.Text = "It\'s possible to execute and create multiple instances.";
            // 
            // groupBoxServiceOperationOption
            // 
            this.groupBoxServiceOperationOption.Controls.Add(this.radioButtonInstallAndRun);
            this.groupBoxServiceOperationOption.Controls.Add(this.radioButtonUninstall);
            this.groupBoxServiceOperationOption.Controls.Add(this.radioButtonInstall);
            this.groupBoxServiceOperationOption.Location = new System.Drawing.Point(14, 292);
            this.groupBoxServiceOperationOption.Name = "groupBoxServiceOperationOption";
            this.groupBoxServiceOperationOption.Size = new System.Drawing.Size(329, 50);
            this.groupBoxServiceOperationOption.TabIndex = 15;
            this.groupBoxServiceOperationOption.TabStop = false;
            this.groupBoxServiceOperationOption.Text = "Service Operation Options";
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(208, 18);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(244, 17);
            this.label9.TabIndex = 26;
            this.label9.Text = "Execute jitGate in Windows NT mode.";
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(8, 21);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(194, 44);
            this.button1.TabIndex = 22;
            this.button1.Text = "Run as Windows NT Service";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // buttonSettings
            // 
            this.buttonSettings.Location = new System.Drawing.Point(257, 668);
            this.buttonSettings.Name = "buttonSettings";
            this.buttonSettings.Size = new System.Drawing.Size(132, 30);
            this.buttonSettings.TabIndex = 19;
            this.buttonSettings.Text = "Settings";
            this.buttonSettings.UseVisualStyleBackColor = true;
            this.buttonSettings.Click += new System.EventHandler(this.buttonSettings_Click);
            // 
            // buttonRunConsole
            // 
            this.buttonRunConsole.Location = new System.Drawing.Point(8, 24);
            this.buttonRunConsole.Name = "buttonRunConsole";
            this.buttonRunConsole.Size = new System.Drawing.Size(194, 44);
            this.buttonRunConsole.TabIndex = 21;
            this.buttonRunConsole.Text = "Run as Console Application";
            this.buttonRunConsole.UseVisualStyleBackColor = true;
            this.buttonRunConsole.Click += new System.EventHandler(this.buttonRunConsole_Click);
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.label13);
            this.groupBox1.Controls.Add(this.label12);
            this.groupBox1.Controls.Add(this.label11);
            this.groupBox1.Controls.Add(this.buttonRunConsole);
            this.groupBox1.Location = new System.Drawing.Point(12, 181);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(563, 88);
            this.groupBox1.TabIndex = 22;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Console application";
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(211, 55);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(145, 17);
            this.label13.TabIndex = 25;
            this.label13.Text = "More details available";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(211, 38);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(270, 17);
            this.label12.TabIndex = 23;
            this.label12.Text = "It\'s possible to execute multiple instances.";
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(211, 21);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(286, 17);
            this.label11.TabIndex = 22;
            this.label11.Text = "Execute jitGate in console application mode.";
            // 
            // textBoxRESTEndpoint
            // 
            this.textBoxRESTEndpoint.Location = new System.Drawing.Point(116, 21);
            this.textBoxRESTEndpoint.Name = "textBoxRESTEndpoint";
            this.textBoxRESTEndpoint.Size = new System.Drawing.Size(434, 22);
            this.textBoxRESTEndpoint.TabIndex = 26;
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(9, 26);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(105, 17);
            this.label14.TabIndex = 27;
            this.label14.Text = "REST Endpoint";
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.textBoxRESTEndpoint);
            this.groupBox2.Controls.Add(this.label14);
            this.groupBox2.Location = new System.Drawing.Point(12, 111);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(563, 64);
            this.groupBox2.TabIndex = 28;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Web API";
            // 
            // propertyGrid1
            // 
            this.propertyGrid1.CategoryForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.propertyGrid1.Location = new System.Drawing.Point(667, 24);
            this.propertyGrid1.Name = "propertyGrid1";
            this.propertyGrid1.Size = new System.Drawing.Size(130, 130);
            this.propertyGrid1.TabIndex = 30;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.linkLabel3);
            this.groupBox3.Controls.Add(this.checkBox2);
            this.groupBox3.Controls.Add(this.linkLabel1);
            this.groupBox3.Controls.Add(this.checkBoxConsole);
            this.groupBox3.Location = new System.Drawing.Point(12, 12);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(649, 98);
            this.groupBox3.TabIndex = 29;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Web API";
            // 
            // linkLabel1
            // 
            this.linkLabel1.AutoSize = true;
            this.linkLabel1.Location = new System.Drawing.Point(170, 56);
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Size = new System.Drawing.Size(39, 17);
            this.linkLabel1.TabIndex = 24;
            this.linkLabel1.TabStop = true;
            this.linkLabel1.Text = "Here";
            // 
            // checkBoxConsole
            // 
            this.checkBoxConsole.AutoSize = true;
            this.checkBoxConsole.Location = new System.Drawing.Point(8, 22);
            this.checkBoxConsole.Name = "checkBoxConsole";
            this.checkBoxConsole.Size = new System.Drawing.Size(308, 55);
            this.checkBoxConsole.TabIndex = 0;
            this.checkBoxConsole.Text = "Execute jitGate in console application mode.\r\nIt\'s possible to execute multiple i" +
    "nstances.\r\nMore details available \r\n";
            this.checkBoxConsole.UseVisualStyleBackColor = true;
            // 
            // linkLabel3
            // 
            this.linkLabel3.AutoSize = true;
            this.linkLabel3.Location = new System.Drawing.Point(485, 56);
            this.linkLabel3.Name = "linkLabel3";
            this.linkLabel3.Size = new System.Drawing.Size(39, 17);
            this.linkLabel3.TabIndex = 29;
            this.linkLabel3.TabStop = true;
            this.linkLabel3.Text = "Here";
            // 
            // checkBox2
            // 
            this.checkBox2.AutoSize = true;
            this.checkBox2.Location = new System.Drawing.Point(322, 22);
            this.checkBox2.Name = "checkBox2";
            this.checkBox2.Size = new System.Drawing.Size(308, 55);
            this.checkBox2.TabIndex = 25;
            this.checkBox2.Text = "Execute jitGate in console application mode.\r\nIt\'s possible to execute multiple i" +
    "nstances.\r\nMore details available ";
            this.checkBox2.UseVisualStyleBackColor = true;
            // 
            // ShowServiceFormSettingCreation
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1118, 709);
            this.ControlBox = false;
            this.Controls.Add(this.propertyGrid1);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.groupBoxRun);
            this.Controls.Add(this.buttonSettings);
            this.Controls.Add(this.buttonCancel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Name = "ShowServiceFormSettingCreation";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "jitGate Host Instance Dialog";
            this.Load += new System.EventHandler(this.ShowServiceFormSettingCreationLoad);
            this.groupBoxAffinity.ResumeLayout(false);
            this.groupBoxAffinity.PerformLayout();
            this.groupBoxRun.ResumeLayout(false);
            this.groupBoxRun.PerformLayout();
            this.groupBoxServiceOperationOption.ResumeLayout(false);
            this.groupBoxServiceOperationOption.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.RadioButton radioButtonFullAffinity;
        private System.Windows.Forms.GroupBox groupBoxAffinity;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox textBoxPassword;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox textBoxUsername;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox textBoxDescription;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBoxDisplayName;
        private System.Windows.Forms.RadioButton radioButtonCustomAffinity;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox textBoxWindowsNTServiceName;
        private System.Windows.Forms.Button buttonClone;
        private System.Windows.Forms.Button buttonCancel;
        private System.Windows.Forms.ComboBox comboBoxAccount;
        private System.Windows.Forms.GroupBox groupBoxRun;
        private System.Windows.Forms.RadioButton radioButtonUninstall;
        private System.Windows.Forms.RadioButton radioButtonInstallAndRun;
        private System.Windows.Forms.RadioButton radioButtonInstall;
        private System.Windows.Forms.GroupBox groupBoxServiceOperationOption;
        private System.Windows.Forms.Button buttonSettings;
        private System.Windows.Forms.Button buttonCreate;
        private System.Windows.Forms.Button buttonRunConsole;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox textBoxRESTEndpoint;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.LinkLabel linkLabel2;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.PropertyGrid propertyGrid1;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.LinkLabel linkLabel3;
        private System.Windows.Forms.CheckBox checkBox2;
        private System.Windows.Forms.LinkLabel linkLabel1;
        private System.Windows.Forms.CheckBox checkBoxConsole;
    }
}