// <auto-generated />
namespace GrabCaster.Framework.Common
{
    using GrabCaster.Framework.NTService;
    using System.ComponentModel;
    using System.ServiceProcess;

    partial class ProjectInstaller
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.coreServiceProcessInstaller = new System.ServiceProcess.ServiceProcessInstaller();
            this.coreServiceInstaller = new System.ServiceProcess.ServiceInstaller();
            // 
            // coreServiceProcessInstaller
            // 
            this.coreServiceProcessInstaller.Account = ServiceAccount.NetworkService;
            // 
            // coreServiceInstaller
            // 
            this.coreServiceInstaller.Description = string.Format("GrabCaster {0} Windows NT Service.", CoreNtService.ServiceName);
            this.coreServiceInstaller.DisplayName = string.Format("GrabCaster {0}", CoreNtService.ServiceName);
            this.coreServiceInstaller.ServiceName = CoreNtService.ServiceName;
            //this.coreServiceProcessInstaller.Account = System.ServiceProcess.ServiceAccount.User;
            //this.coreServiceProcessInstaller.Password = "password";
            //this.coreServiceProcessInstaller.Username = "machinename\\admin";
            //// 
            //// coreServiceInstaller
            //// 
            //this.coreServiceInstaller.Description = "core Host Instance";
            //this.coreServiceInstaller.DisplayName = "coreDefault";
            //this.coreServiceInstaller.WindowsNTServiceName = "coreDefault";

            // 
            // ProjectInstaller
            // 
            this.Installers.AddRange(new System.Configuration.Install.Installer[] {
            this.coreServiceProcessInstaller,
            this.coreServiceInstaller});

        }

        #endregion

        public ServiceProcessInstaller coreServiceProcessInstaller;
        public ServiceInstaller coreServiceInstaller;
    }
}